const PERMISSIONS = Object.freeze({
  VIEW_OPERATION_DASHBOARD: 'VIEW_OPERATION_DASHBOARD',
  VIEW_REVENUE: 'VIEW_REVENUE',
  VIEW_BOOKINGS: 'VIEW_BOOKINGS',
  MANAGE_BOOKINGS: 'MANAGE_BOOKINGS',
  MARK_NO_SHOW: 'MARK_NO_SHOW',
  PRINT_BOOKING: 'PRINT_BOOKING',
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  EDIT_CUSTOMERS: 'EDIT_CUSTOMERS',
  VIEW_BUSES: 'VIEW_BUSES',
  VIEW_TRIPS: 'VIEW_TRIPS',
  EDIT_TRIPS: 'EDIT_TRIPS',
  CREATE_TRIPS: 'CREATE_TRIPS',
  DELETE_TRIPS: 'DELETE_TRIPS',
  VIEW_ROUTES: 'VIEW_ROUTES',
  EDIT_ROUTES: 'EDIT_ROUTES',
  CREATE_ROUTES: 'CREATE_ROUTES',
  DELETE_ROUTES: 'DELETE_ROUTES',
  MANAGE_BUSES: 'MANAGE_BUSES',
  MANAGE_NEWS: 'MANAGE_NEWS',
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_SYSTEM_LOGS: 'VIEW_SYSTEM_LOGS',
  MANAGE_SYSTEM_SETTINGS: 'MANAGE_SYSTEM_SETTINGS',
  EXPORT_DATA: 'EXPORT_DATA',
})

const STAFF_PERMISSIONS = Object.freeze([
  PERMISSIONS.VIEW_OPERATION_DASHBOARD,
  PERMISSIONS.VIEW_BOOKINGS,
  PERMISSIONS.MANAGE_BOOKINGS,
  PERMISSIONS.MARK_NO_SHOW,
  PERMISSIONS.PRINT_BOOKING,
  PERMISSIONS.VIEW_CUSTOMERS,
  PERMISSIONS.EDIT_CUSTOMERS,
  PERMISSIONS.VIEW_BUSES,
  PERMISSIONS.VIEW_TRIPS,
  PERMISSIONS.EDIT_TRIPS,
  PERMISSIONS.VIEW_ROUTES,
  PERMISSIONS.EDIT_ROUTES,
  PERMISSIONS.MANAGE_NEWS,
])

const ROLE_LABELS = Object.freeze({
  ADMIN: 'Chủ xe',
  STAFF: 'Nhân viên quản trị',
  CUSTOMER: 'Khách hàng',
})

const ROLE_PERMISSIONS = Object.freeze({
  ADMIN: Object.freeze(Object.values(PERMISSIONS)),
  STAFF: STAFF_PERMISSIONS,
  CUSTOMER: Object.freeze([]),
})

const getPermissionsForRole = (role) => [...(ROLE_PERMISSIONS[role] || [])]

const hasPermission = (role, permission) =>
  ROLE_PERMISSIONS[role]?.includes(permission) || false

export {
  PERMISSIONS,
  ROLE_LABELS,
  ROLE_PERMISSIONS,
  getPermissionsForRole,
  hasPermission,
}
