const PERMISSIONS = Object.freeze({
  VIEW_OPERATION_DASHBOARD: 'VIEW_OPERATION_DASHBOARD',
  VIEW_REVENUE: 'VIEW_REVENUE',
  VIEW_BOOKINGS: 'VIEW_BOOKINGS',
  MANAGE_BOOKINGS: 'MANAGE_BOOKINGS',
  MARK_NO_SHOW: 'MARK_NO_SHOW',
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  EDIT_CUSTOMERS: 'EDIT_CUSTOMERS',
  MANAGE_CUSTOMER_STATUS: 'MANAGE_CUSTOMER_STATUS',
  VIEW_BUSES: 'VIEW_BUSES',
  VIEW_TRIPS: 'VIEW_TRIPS',
  EDIT_TRIPS: 'EDIT_TRIPS',
  CREATE_TRIPS: 'CREATE_TRIPS',
  DELETE_TRIPS: 'DELETE_TRIPS',
  VIEW_ROUTES: 'VIEW_ROUTES',
  EDIT_ROUTES: 'EDIT_ROUTES',
  CREATE_ROUTES: 'CREATE_ROUTES',
  DELETE_ROUTES: 'DELETE_ROUTES',
  MANAGE_BUSES: 'MANAGE_BUSES',
  MANAGE_NEWS: 'MANAGE_NEWS',
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_SYSTEM_LOGS: 'VIEW_SYSTEM_LOGS',
})

const ROLE_LABELS = Object.freeze({
  ADMIN: 'Chủ xe',
  STAFF: 'Nhân viên quản trị',
  CUSTOMER: 'Khách hàng',
})

const hasPermission = (user, permission) =>
  user?.role === 'ADMIN' || user?.permissions?.includes(permission) || false

export { hasPermission, PERMISSIONS, ROLE_LABELS }
