import { Link } from 'react-router-dom'
import { useCallback, useEffect, useMemo, useState } from 'react'
import AdminPageHeader from '../../components/admin/AdminPageHeader.jsx'
import { EmptyState, ErrorState, LoadingState } from '../../components/common/StatusState.jsx'
import { useAuth } from '../../contexts/authContext.js'
import { exportCustomersExcel, getCustomers } from '../../services/admin.service.js'
import { getApiErrorMessage } from '../../services/apiClient.js'
import formatCurrency from '../../utils/formatCurrency.js'
import { formatDateTime } from '../../utils/formatDateTime.js'
import { formatPhoneInput } from '../../utils/normalizers.js'

const CLASSIFICATION_LABELS = { VIP: 'VIP', REGULAR: 'Thường xuyên', NEW: 'Mới' }
const getCustomerStatusLabel = (status) => status === 'BLOCKED' ? 'Đã khóa' : status === 'ARCHIVED' ? 'Lưu trữ' : 'Hoạt động'
const getViolationClass = (violations) => violations?.level === 'BLOCKED' ? 'status-badge status-badge--cancelled' : violations?.level === 'WARNING' ? 'status-badge status-badge--pending' : 'status-badge status-badge--active'
const downloadBlob = (response, fileName) => { const url = window.URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = fileName; document.body.appendChild(link); link.click(); link.remove(); window.URL.revokeObjectURL(url) }

function AdminCustomersPage() {
  const { user } = useAuth(); const isAdmin = user?.role === 'ADMIN'
  const [data, setData] = useState(null); const [filters, setFilters] = useState({ keyword: '', status: '', classification: '', sortBy: 'newest' }); const [appliedFilters, setAppliedFilters] = useState({ keyword: '', status: '', classification: '', sortBy: 'newest' }); const [page, setPage] = useState(1); const [error, setError] = useState(''); const [exporting, setExporting] = useState(false)
  const load = useCallback(async () => { setError(''); try { const result = await getCustomers({ page, limit: 10, ...(appliedFilters.keyword.trim() && { keyword: appliedFilters.keyword.trim() }), ...(appliedFilters.status && { status: appliedFilters.status }), ...(appliedFilters.classification && { classification: appliedFilters.classification }), sortBy: appliedFilters.sortBy }); setData(result) } catch (e) { setError(getApiErrorMessage(e)) } }, [appliedFilters, page])
  useEffect(() => { load() }, [load])
  const customers = useMemo(() => data?.customers ?? [], [data?.customers])
  const summary = data?.summary ?? { total: data?.pagination?.total ?? 0, active: 0, blocked: 0, vip: 0, warning: 0, newThisMonth: 0, totalSpent: 0 }
  const submitFilter = (event) => { event.preventDefault(); setPage(1); setAppliedFilters(filters) }
  const clearFilter = () => { const next = { keyword: '', status: '', classification: '', sortBy: 'newest' }; setFilters(next); setAppliedFilters(next); setPage(1) }
  const handleExport = async () => { setExporting(true); try { const response = await exportCustomersExcel(); downloadBlob(response, `DanhSachKhachHang_${new Date().toISOString().slice(0, 10)}.xlsx`) } catch (e) { window.alert(getApiErrorMessage(e)) } finally { setExporting(false) } }

  return <>
    <AdminPageHeader title="Khách hàng" description="Danh sách khách hàng. Sửa và xóa/lưu trữ mở ở trang riêng." />
    <div className="admin-stat-grid"><article className="admin-stat-card"><span>Tổng khách hàng</span><strong>{summary.total}</strong></article><article className="admin-stat-card"><span>Khách VIP</span><strong>{summary.vip}</strong></article><article className="admin-stat-card admin-stat-card--refund"><span>Đã khóa</span><strong>{summary.blocked}</strong></article><article className="admin-stat-card"><span>Cần cảnh báo</span><strong>{summary.warning}</strong></article><article className="admin-stat-card"><span>Khách mới tháng này</span><strong>{summary.newThisMonth}</strong></article>{isAdmin && <article className="admin-stat-card admin-stat-card--money"><span>Tổng chi tiêu</span><strong>{formatCurrency(summary.totalSpent)}</strong></article>}</div>
    <form className="admin-filter-bar" onSubmit={submitFilter}><input className="form-control" value={filters.keyword} onChange={(e) => setFilters((c) => ({ ...c, keyword: e.target.value }))} placeholder="Mã, tên, email hoặc số điện thoại" /><select className="form-select" value={filters.classification} onChange={(e) => setFilters((c) => ({ ...c, classification: e.target.value }))}><option value="">Tất cả phân loại</option><option value="VIP">VIP</option><option value="REGULAR">Thường xuyên</option><option value="NEW">Mới</option></select><select className="form-select" value={filters.status} onChange={(e) => setFilters((c) => ({ ...c, status: e.target.value }))}><option value="">Tất cả trạng thái</option><option value="ACTIVE">Hoạt động</option><option value="BLOCKED">Đã khóa</option>{isAdmin && <option value="ARCHIVED">Lưu trữ</option>}</select><select className="form-select" value={filters.sortBy} onChange={(e) => setFilters((c) => ({ ...c, sortBy: e.target.value }))}><option value="newest">Mới tạo</option><option value="bookings">Số vé thành công</option><option value="spending">Chi tiêu cao nhất</option><option value="recent">Đặt gần nhất</option><option value="name">Tên A → Z</option></select><div className="d-flex gap-2"><button className="btn btn-primary" type="submit">Lọc dữ liệu</button><button className="btn btn-outline-secondary" onClick={clearFilter} type="button">Xóa lọc</button>{isAdmin && <button className="btn btn-outline-success" disabled={exporting} onClick={handleExport} type="button">{exporting ? 'Đang xuất...' : 'Xuất Excel'}</button>}</div></form>
    {error ? <ErrorState message={error} onRetry={load} /> : !data ? <LoadingState /> : customers.length === 0 ? <EmptyState message="Chưa có khách hàng phù hợp." /> : <section className="admin-panel"><div className="admin-panel__heading"><div><h2>Danh sách khách hàng</h2><p>VIP: ≥10 vé thành công hoặc ≥5 triệu; Thường xuyên: ≥3 vé hoặc ≥1,5 triệu.</p></div><strong>{data.pagination?.total ?? customers.length} kết quả</strong></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Mã KH</th><th>Khách hàng</th><th>Phân loại</th><th>Vé thành công</th><th>Vi phạm</th><th>Chi tiêu</th><th>Tuyến thường đi</th><th>Đặt gần nhất</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{customers.map((customer) => <tr key={customer.id}><td><strong>{customer.id.slice(0, 8).toUpperCase()}</strong></td><td><strong>{customer.fullName}</strong><small>{formatPhoneInput(customer.phone)} · {customer.email || 'Chưa có email'}</small></td><td><span className="status-badge">{CLASSIFICATION_LABELS[customer.classification] || customer.classification}</span></td><td><strong>{customer.successfulBookings ?? 0}</strong><small>Tổng vé: {customer.totalBookings ?? 0}</small></td><td><span className={getViolationClass(customer.violations)}>{customer.violations?.label || 'Bình thường'} ({customer.violations?.count ?? 0})</span></td><td><strong>{isAdmin ? formatCurrency(customer.totalSpent) : '—'}</strong></td><td>{customer.favoriteRoute || '-'}</td><td>{customer.lastBookingAt ? formatDateTime(customer.lastBookingAt) : 'Chưa đặt'}</td><td><span className={`status-badge status-badge--${customer.status === 'ACTIVE' ? 'active' : 'cancelled'}`}>{getCustomerStatusLabel(customer.status)}</span></td><td><div className="admin-row-actions"><Link to={`/admin/khach-hang/${customer.id}`}>Chi tiết</Link><Link to={`/admin/khach-hang/${customer.id}/sua`}>Sửa</Link>{isAdmin && customer.status !== 'ARCHIVED' && <Link className="is-danger" to={`/admin/khach-hang/${customer.id}/xoa`}>Xóa/Lưu trữ</Link>}</div></td></tr>)}</tbody></table></div>{(data.pagination?.totalPages ?? 1) > 1 && <div className="admin-pagination"><button className="btn btn-outline-secondary" disabled={page <= 1} onClick={() => setPage((c) => c - 1)} type="button">Trang trước</button><strong>Trang {data.pagination.page}/{data.pagination.totalPages}</strong><button className="btn btn-outline-secondary" disabled={page >= data.pagination.totalPages} onClick={() => setPage((c) => c + 1)} type="button">Trang sau</button></div>}</section>}
  </>
}
export default AdminCustomersPage
