import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import AdminPageHeader from '../../components/admin/AdminPageHeader.jsx'
import { ErrorState, LoadingState } from '../../components/common/StatusState.jsx'
import { getBookingDetail, updateBookingContact } from '../../services/admin.service.js'
import { getApiErrorMessage } from '../../services/apiClient.js'
import { formatBookingCode, formatPhoneInput, isValidFullName, isVietnamesePhone, normalizeFullName, normalizePhone } from '../../utils/normalizers.js'

function AdminBookingEditPage() {
  const { bookingCode } = useParams(); const navigate = useNavigate(); const [booking, setBooking] = useState(null); const [form, setForm] = useState({ passengerFullName: '', passengerPhone: '', staffNote: '' }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { const result = await getBookingDetail(bookingCode); const data = result?.booking ?? result; if (!data?.bookingCode) throw new Error('Không tìm thấy vé.'); setBooking(data); setForm({ passengerFullName: data.passengerFullName ?? '', passengerPhone: formatPhoneInput(data.passengerPhone ?? ''), staffNote: data.staffNote ?? '' }) } catch (e) { setError(getApiErrorMessage(e)) } finally { setLoading(false) } }, [bookingCode])
  useEffect(() => { load() }, [load])
  const submit = async (event) => { event.preventDefault(); const passengerFullName = normalizeFullName(form.passengerFullName); const passengerPhone = normalizePhone(form.passengerPhone); if (!isValidFullName(passengerFullName)) return setError('Họ tên hành khách không hợp lệ.'); if (!isVietnamesePhone(passengerPhone)) return setError('Số điện thoại Việt Nam không hợp lệ. Ví dụ: 0912 345 678.'); setSaving(true); setError(''); try { await updateBookingContact(bookingCode, { passengerFullName, passengerPhone, staffNote: form.staffNote.trim() }); navigate(`/admin/ve-xe/${bookingCode}`, { replace: true }) } catch (e) { setError(getApiErrorMessage(e)) } finally { setSaving(false) } }
  if (loading) return <LoadingState />
  if (!booking) return <ErrorState message={error || 'Không tìm thấy vé.'} onRetry={load} />
  return <div className="admin-crud-page"><AdminPageHeader title="Sửa thông tin vé" description={`Mã vé: ${formatBookingCode(booking.bookingCode)}`} /><section className="admin-panel">{error && <div className="alert alert-danger">{error}</div>}<div className="alert alert-info">Chỉ chỉnh sửa thông tin hành khách và ghi chú; chuyến và ghế/phòng không thay đổi tại đây.</div><form className="admin-form-grid" onSubmit={submit}><label className="admin-field"><span>Họ và tên</span><input className="form-control" required value={form.passengerFullName} onChange={(e) => setForm((c) => ({ ...c, passengerFullName: e.target.value }))} /></label><label className="admin-field"><span>Số điện thoại</span><input className="form-control" inputMode="tel" maxLength={12} required value={form.passengerPhone} onChange={(e) => setForm((c) => ({ ...c, passengerPhone: formatPhoneInput(e.target.value) }))} /></label><label className="admin-field admin-field--wide"><span>Ghi chú nhân viên</span><textarea className="form-control" rows="4" maxLength="1000" value={form.staffNote} onChange={(e) => setForm((c) => ({ ...c, staffNote: e.target.value }))} /></label><div className="admin-field admin-field--wide admin-crud-actions"><Link className="btn btn-outline-secondary" to={`/admin/ve-xe/${bookingCode}`}>Hủy</Link><button className="btn btn-primary" disabled={saving} type="submit">{saving ? 'Đang lưu...' : 'Lưu thay đổi'}</button></div></form></section></div>
}
export default AdminBookingEditPage
