import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import AdminDeleteConfirm from '../../components/admin/AdminDeleteConfirm.jsx'
import AdminPageHeader from '../../components/admin/AdminPageHeader.jsx'
import { ErrorState, LoadingState } from '../../components/common/StatusState.jsx'
import { createLocationArea, createProvince, createSpecificLocation, deleteLocationArea, deleteSpecificLocation, getLocationCatalog, updateLocationArea, updateProvince, updateSpecificLocation } from '../../services/admin.service.js'
import { getApiErrorMessage } from '../../services/apiClient.js'
import { normalizeAddress, normalizeLocationName, normalizeProvince, normalizeWhitespace } from '../../utils/normalizers.js'

const TYPE_LABELS = { province: 'Tỉnh/Thành', area: 'Bộ lọc địa điểm', location: 'Địa điểm cụ thể' }
const STATUS_LABELS = { ACTIVE: 'Hoạt động', INACTIVE: 'Ngừng' }
const LOCATION_TYPE_LABELS = { PICKUP: 'Điểm đón', DROPOFF: 'Điểm trả', BOTH: 'Cả điểm đón và điểm trả' }
const EMPTY = { province: { name: '', status: 'ACTIVE' }, area: { provinceId: '', name: '', sortOrder: '0', status: 'ACTIVE' }, location: { provinceId: '', filterAreaIds: [], defaultAreaId: '', name: '', address: '', locationType: 'BOTH', status: 'ACTIVE' } }
const getFilterAreaIds = (location) => { const ids = (location?.areaFilters || []).map((filter) => filter.areaId || filter.area?.id).filter(Boolean); if (location?.defaultAreaId && !ids.includes(location.defaultAreaId)) ids.push(location.defaultAreaId); return [...new Set(ids)] }

function AdminLocationEntityPage({ entityType, mode = 'create' }) {
  const { id } = useParams(); const navigate = useNavigate(); const editing = mode === 'edit'; const deleting = mode === 'delete'; const [catalog, setCatalog] = useState({ provinces: [], areas: [], locations: [] }); const [form, setForm] = useState({ ...EMPTY[entityType] }); const [record, setRecord] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const backTo = '/admin/dia-diem'
  const load = useCallback(async () => { setLoading(true); setError(''); try { const data = await getLocationCatalog(); const next = { provinces: data?.provinces ?? [], areas: data?.areas ?? [], locations: data?.locations ?? [] }; setCatalog(next); if (editing || deleting) { const source = entityType === 'province' ? next.provinces : entityType === 'area' ? next.areas : next.locations; const found = source.find((row) => row.id === id); if (!found) throw new Error(`Không tìm thấy ${TYPE_LABELS[entityType].toLowerCase()}.`); setRecord(found); if (editing) { if (entityType === 'province') setForm({ name: found.name || '', status: found.status || 'ACTIVE' }); else if (entityType === 'area') setForm({ provinceId: found.provinceId || found.province?.id || '', name: found.name || '', sortOrder: String(found.sortOrder ?? 0), status: found.status || 'ACTIVE' }); else setForm({ provinceId: found.provinceId || found.provinceRef?.id || '', filterAreaIds: getFilterAreaIds(found), defaultAreaId: found.defaultAreaId || found.defaultArea?.id || '', name: found.name || '', address: found.address || '', locationType: found.locationType || 'BOTH', status: found.status || 'ACTIVE' }) } } } catch (e) { setError(getApiErrorMessage(e)) } finally { setLoading(false) } }, [deleting, editing, entityType, id])
  useEffect(() => { load() }, [load])
  const activeProvinces = useMemo(() => catalog.provinces.filter((province) => province.status === 'ACTIVE' || province.id === form.provinceId), [catalog.provinces, form.provinceId])
  const areaOptions = useMemo(() => catalog.areas.filter((area) => area.provinceId === form.provinceId && (area.status === 'ACTIVE' || form.filterAreaIds?.includes(area.id) || form.defaultAreaId === area.id)), [catalog.areas, form.defaultAreaId, form.filterAreaIds, form.provinceId])

  const submit = async (event) => {
    event.preventDefault(); setSaving(true); setError('')
    try {
      if (entityType === 'province') { const name = normalizeProvince(form.name); if (!name) throw new Error('Vui lòng nhập tên tỉnh/thành.'); if (editing) await updateProvince(id, { name, status: form.status }); else await createProvince({ name }) }
      if (entityType === 'area') { const payload = { provinceId: form.provinceId, name: normalizeWhitespace(form.name), sortOrder: Number(form.sortOrder || 0), status: form.status }; if (!payload.provinceId || !payload.name) throw new Error('Vui lòng chọn tỉnh/thành và nhập tên bộ lọc.'); if (editing) await updateLocationArea(id, payload); else await createLocationArea(payload) }
      if (entityType === 'location') { const filterAreaIds = [...new Set([form.defaultAreaId, ...(form.filterAreaIds || [])].filter(Boolean))]; const payload = { provinceId: form.provinceId, filterAreaIds, defaultAreaId: form.defaultAreaId, name: normalizeLocationName(form.name), address: normalizeAddress(form.address) || undefined, locationType: form.locationType, status: form.status }; if (!payload.provinceId || !payload.defaultAreaId || !payload.name) throw new Error('Vui lòng chọn tỉnh/thành, bộ lọc mặc định và nhập tên địa điểm.'); if (!filterAreaIds.length) throw new Error('Vui lòng chọn ít nhất một bộ lọc áp dụng.'); if (editing) await updateSpecificLocation(id, payload); else await createSpecificLocation(payload) }
      navigate(backTo, { replace: true })
    } catch (e) { setError(getApiErrorMessage(e)) } finally { setSaving(false) }
  }

  const confirmDelete = async () => { setSaving(true); setError(''); try { if (entityType === 'area') await deleteLocationArea(id); else if (entityType === 'location') await deleteSpecificLocation(id); else throw new Error('Tỉnh/Thành không hỗ trợ xóa; hãy chuyển trạng thái sang Ngừng.'); navigate(backTo, { replace: true }) } catch (e) { setError(getApiErrorMessage(e)); setSaving(false) } }

  if (loading) return <LoadingState />
  if ((editing || deleting) && !record) return <ErrorState message={error || `Không tìm thấy ${TYPE_LABELS[entityType]}.`} onRetry={load} />
  if (deleting) return <div className="admin-crud-page"><AdminPageHeader title={`Xóa ${TYPE_LABELS[entityType]}`} description="Xác nhận xóa mềm ở trang riêng." />{error && <div className="alert alert-danger">{error}</div>}<AdminDeleteConfirm title={`Xóa ${record?.name || TYPE_LABELS[entityType]}`} warning="Dữ liệu lịch sử liên quan vẫn được giữ theo nghiệp vụ hiện tại." rows={[{ label: 'Tên', value: record?.name }, { label: 'Tỉnh/Thành', value: record?.province?.name || record?.provinceRef?.name || record?.province || '—' }, { label: 'Trạng thái', value: STATUS_LABELS[record?.status] || 'Không xác định' }, { label: 'Loại', value: record?.locationType ? LOCATION_TYPE_LABELS[record.locationType] : TYPE_LABELS[entityType] }]} backTo={backTo} processing={saving} onConfirm={confirmDelete} /></div>

  const title = `${editing ? 'Sửa' : 'Thêm'} ${TYPE_LABELS[entityType]}`
  return <div className="admin-crud-page"><AdminPageHeader title={title} description="Biểu mẫu được mở ở trang riêng, không chen vào danh sách địa điểm." /><section className="admin-panel">{error && <div className="alert alert-danger">{error}</div>}<form className="admin-form-grid" onSubmit={submit}>
    {entityType === 'province' && <><label className="admin-field admin-field--wide"><span>Tên Tỉnh/Thành</span><input className="form-control" maxLength={120} required value={form.name} onChange={(e) => setForm((c) => ({ ...c, name: e.target.value }))} /></label>{editing && <label className="admin-field"><span>Trạng thái</span><select className="form-select" value={form.status} onChange={(e) => setForm((c) => ({ ...c, status: e.target.value }))}><option value="ACTIVE">Hoạt động</option><option value="INACTIVE">Ngừng</option></select></label>}</>}
    {entityType === 'area' && <><label className="admin-field"><span>Tỉnh/Thành</span><select className="form-select" required value={form.provinceId} onChange={(e) => setForm((c) => ({ ...c, provinceId: e.target.value }))}><option value="">-- Chọn --</option>{activeProvinces.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="admin-field"><span>Tên bộ lọc</span><input className="form-control" required value={form.name} onChange={(e) => setForm((c) => ({ ...c, name: e.target.value }))} /></label><label className="admin-field"><span>Thứ tự</span><input className="form-control" min="0" type="number" value={form.sortOrder} onChange={(e) => setForm((c) => ({ ...c, sortOrder: e.target.value }))} /></label><label className="admin-field"><span>Trạng thái</span><select className="form-select" value={form.status} onChange={(e) => setForm((c) => ({ ...c, status: e.target.value }))}><option value="ACTIVE">Hoạt động</option><option value="INACTIVE">Ngừng</option></select></label></>}
    {entityType === 'location' && <><label className="admin-field"><span>Tỉnh/Thành</span><select className="form-select" required value={form.provinceId} onChange={(e) => setForm((c) => ({ ...c, provinceId: e.target.value, filterAreaIds: [], defaultAreaId: '' }))}><option value="">-- Chọn --</option>{activeProvinces.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="admin-field"><span>Bộ lọc mặc định</span><select className="form-select" disabled={!form.provinceId} required value={form.defaultAreaId} onChange={(e) => { const defaultAreaId = e.target.value; setForm((c) => ({ ...c, defaultAreaId, filterAreaIds: defaultAreaId && !c.filterAreaIds.includes(defaultAreaId) ? [...c.filterAreaIds, defaultAreaId] : c.filterAreaIds })) }}><option value="">-- Chọn --</option>{areaOptions.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><div className="admin-field admin-field--wide"><span>Bộ lọc áp dụng</span><div className="admin-location-filter-checks">{areaOptions.length === 0 ? <small>Chưa có bộ lọc thuộc tỉnh/thành này.</small> : areaOptions.map((area) => <label key={area.id}><input checked={form.filterAreaIds.includes(area.id)} disabled={area.id === form.defaultAreaId} onChange={() => setForm((c) => ({ ...c, filterAreaIds: c.filterAreaIds.includes(area.id) ? c.filterAreaIds.filter((value) => value !== area.id) : [...c.filterAreaIds, area.id] }))} type="checkbox" /><span>{area.name}</span>{area.id === form.defaultAreaId && <small>Mặc định</small>}</label>)}</div></div><label className="admin-field"><span>Tên địa điểm</span><input className="form-control" maxLength={200} required value={form.name} onChange={(e) => setForm((c) => ({ ...c, name: e.target.value }))} /></label><label className="admin-field"><span>Loại địa điểm</span><select className="form-select" value={form.locationType} onChange={(e) => setForm((c) => ({ ...c, locationType: e.target.value }))}>{Object.entries(LOCATION_TYPE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="admin-field admin-field--wide"><span>Địa chỉ chi tiết</span><input className="form-control" maxLength={300} value={form.address} onChange={(e) => setForm((c) => ({ ...c, address: e.target.value }))} /></label><label className="admin-field"><span>Trạng thái</span><select className="form-select" value={form.status} onChange={(e) => setForm((c) => ({ ...c, status: e.target.value }))}><option value="ACTIVE">Hoạt động</option><option value="INACTIVE">Ngừng</option></select></label></>}
    <div className="admin-field admin-field--wide admin-crud-actions"><Link className="btn btn-outline-secondary" to={backTo}>Hủy</Link><button className="btn btn-primary" disabled={saving} type="submit">{saving ? 'Đang lưu...' : editing ? 'Lưu thay đổi' : `Thêm ${TYPE_LABELS[entityType]}`}</button></div>
  </form></section></div>
}
export default AdminLocationEntityPage
